### PR TITLE
Feature stream requests

### PR DESCRIPTION
**Pull request by RomarQ**
Added support to rpc stream request and fixed some more conflicts introduced by commit `fdded22a8ef2bd906d74fdc0b9555fccb4ff5582`

With this commit, issue #87 can be closed.

**Example of a stream request added with this pull request**
```
func monitorHeads(rpc *goTezos.GoTezos, db *sql.DB, chainID string) error {
	for {
                // Channels to allow communication with the go routine
		heads := make(chan block.Header)
		errc := make(chan error)
		done := make(chan bool)
               
                // Go routine that will start a stream request and send the results to the channels 
		go rpc.Node.MonitorHeads(chainID, heads, errc, done)

                defer close(heads)
                defer close(errc)
                defer close(done)

		for {
                        // This channel receives nil on success
			err := <-errc
                        // This channel receives the header of the new block or nil a error happened
			header := <-heads
			if err != nil {
				return err
				break
			}

			go addBlockResume(rpc, db, header.Level)

			// Update Constants just to avoid incorrect values if the protocol changes
			constants, err := rpc.Network.GetConstants()
			if err != nil {
				return err
			} else {
				rpc.Constants = constants
			}
		}
	}
}
```

### CODE REVIEW

**Comment by tulpenhaendler** [comment]
It is strange to receive that you have to receive the err even if it is nil,
consider sending an error via errc only if it is not nil

**Comment by tulpenhaendler** [comment]
and i would create the channels inside rpc.Node.MonitorHeads and then return them, saves some code, but that is personal preference

**Comment by RomarQ** [comment]
It can be improved for sure, but was how I implemented it for my use case and it works flawlessly.

**Comment by tulpenhaendler** [comment]
OK but just for the future this could be solved with a select clause more elegantly

**Pull request closed without merging**
