### PR TITLE
Attempts at Caching

### PR DESCRIPTION
**Pull request by utdrmac**
Let me know what you think of this simplistic caching implementation. I didn't bother with any mutex/structs because none of these functions are called async by go routines; it's all pretty procedural. If you think it needs something along the lines of cache-timeout-ttl, I have an implementation in mind for that.

### CODE REVIEW

**Comment by tulpenhaendler** [comment]
I am not happy with this, you don`t limit the max size of the cache

I recommend using some premade last recently used cache
https://github.com/hashicorp/golang-lru
also lru is probably the best caching strategy for this anyway

**Comment by utdrmac** [comment]
@tulpenhaendler Can you present a use-case where you see my simplistic cache becoming an issue that would require such (what I consider to be) overkill implementation? Can you also explain why you believe LRU is the best caching strategy here? I am only caching the chain head, which can never be more than 1, and only caching internal-to-the-library snapshot metadata for only those cycles requested. If the user's app only queries 1 cycle, then only 1 is cached, 1 time.

**Comment by utdrmac** [comment]
I like the idea of generic caching, but I'd still like to cache certain aspects of the _/head/_ block. The application that I'm writing with this library is for baker rewards payments. The script calls _GetRewardsForDelegateCycle()_, passing the cycle on which to make payments. That func gets bakers' frozen rewards value, and a list of delegators for that cycle. The library then calls GetDelegationsForDelegateByCycle() for each delegator the baker has, say 100. For each 100 delegators, that func makes 3 RPC calls: fetching the snapshot block for the cycle, fetching the hash of that block, and finally fetching the delegators balance. Those first 2 fetches result in the same answer for all delegates, so makes sense to cache that result. But the last fetch would always return something different because it is specific to each delegator.

It seemed to me that there would be more exceptions/misses to the caching if I implemented something generic, rather than caching the 1 thing just about every func in the library calls, _GetChainHead()_.

I would consider a more robust/complete caching if there were applications using this library that could be viewed as "long term" (like a daemon process, where the head block might change during the running of the app) rather than "1-shot", like a payment script.

Does my reasoning make sense?

**Comment by utdrmac** [comment]
Ok. I need to rethink this. I'm writing new functionality into the library so you can wait for operations to be included. This means that every X seconds, I'll have to call GetChainHead(). If that is cached like I have it now then I'll always return that head block, even if it is not the latest head.

I don't think the LRU cache will help here. I think I need some sort of TTL-style cache.

**Comment by tulpenhaendler** [comment]
I just would exclude all calls that include /head/ instead of a specific blockhash from the cache entirely,
Also I am not sure about this, but i think the rpc allows for long polling of new block heads, that would probably be more efficent than calls every x sec.

about your previous comment, "I would consider a more robust/complete caching if there were applications using this library that could be viewed as "long term" : I dont think a library like this should make any assumptions about how it is used and caching should reflect that, maybe one option would be to inject a cache from the outside, or at least configure it.

**Comment by utdrmac** [comment]
If you could find that polling in the RPC, I'd appreciate it. I traced how the tezos-client uses `wait for ... to be included` and it looks like it just waits some number of seconds before querying `head` again.

**Comment by utdrmac** [comment]
Here's why I think `head` deserves _some_ caching: https://gist.github.com/utdrmac/9911e1318781d81812223182f9639a90

```
$ ./testing 2>&1 | cut -d" " -f3,4 | sort | uniq -c
 102 GetBlockAtLevel 87040
  51 GetBlockAtLevel 92161
 204 GetChainHead()
  51 GetSnapShot 45
```

So many repetitive calls to the same functions which in turn make the same number of RPC calls to the node. The naive caching I did reduces to this:

```
  52 GetBlockAtLevel 87040
   1 GetBlockAtLevel 92161
   1 GetChainHead()
  53 GetChainHead() (Cached)
   1 GetSnapShot 45
  50 GetSnapShot 45 (Cached)
```

Either need to implement a better caching with TTL or need to find a way to reduce the number of repetitive calls to same functions.

**Pull request merged**
